exp: MinimalPair

mode: 
    - evaluate
    - analyze

models:
    hf_masked_model:
      - google-bert/bert-base-multilingual-cased

resultsfpath: ./midterm-replication-jordan-renzo/predictions/pred_npi_across_inanim.tsv
datafpath: ./midterm-replication-jordan-renzo/test_cases/eval_tsv_files/english/npi_across_inanim.tsv
resultsfpath: ./midterm-replication-jordan-renzo/results/results_npi_across_inanim.tsv
save: by_word, by_pair, by_cond
