exp: MinimalPair

mode: 
    - evaluate
    - analyze

models:
    hf_causal_model:
      - mbert-base-multilingual-cased

predfpath: ./predictions/pred_npi_across_inanim.tsv
datafpath: ./data/./test_cases/eval_tsv_files/english/npi_across_inanim.tsv
resultsfpath: ./results/results_npi_across_inanim.tsv
save: by_word, by_pair, by_cond
