exp: MinimalPair

mode: 
    - evaluate
    - analyze

models:
    hf_causal_model:
      - mbert-base-multilingual-cased

predfpath: ./predictions/pred_obj_rel_no_comp_across_anim.tsv
datafpath: ./data/./test_cases/eval_tsv_files/english/obj_rel_no_comp_across_anim.tsv
resultsfpath: ./results/results_obj_rel_no_comp_across_anim.tsv
save: by_word, by_pair, by_cond
