exp: MinimalPair

mode: 
    - evaluate
    - analyze

models:
    hf_causal_model:
      - mbert-base-multilingual-cased

predfpath: ./predictions/pred_reflexives_across.tsv
datafpath: ./test_cases/eval_tsv_files/english/reflexives_across.tsv
resultsfpath: ./results/results_reflexives_across.tsv
save: by_word, by_pair, by_cond
