exp: MinimalPair

mode: 
    - evaluate
    - analyze

models:
    hf_masked_model:
      - google-bert/bert-base-multilingual-cased

predfpath: ./midterm-replication-jordan-renzo/predictions/pred_reflexive_sent_comp.tsv
datafpath: ./midterm-replication-jordan-renzo/test_cases/eval_tsv_files/english/reflexive_sent_comp.tsv
resultsfpath: ./midterm-replication-jordan-renzo/results/results_reflexive_sent_comp.tsv
save: by_word, by_pair, by_cond
