exp: MinimalPair

mode: 
    - evaluate
    - analyze

models:
    hf_causal_model:
      - mbert-base-multilingual-cased

predfpath: ./predictions/pred_sent_comp.tsv
datafpath: ./data/./test_cases/eval_tsv_files/english/sent_comp.tsv
resultsfpath: ./results/results_sent_comp.tsv
save: by_word, by_pair, by_cond
