exp: MinimalPair

mode: 
    - evaluate
    - analyze

models:
    hf_causal_model:
      - mbert-base-multilingual-cased

predfpath: ./predictions/pred_simple_npi_anim.tsv
datafpath: ./test_cases/eval_tsv_files/english/simple_npi_anim.tsv
resultsfpath: ./results/results_simple_npi_anim.tsv
save: by_word, by_pair, by_cond
