exp: MinimalPair

mode: 
    - evaluate
    - analyze

models:
    hf_causal_model:
      - google-bert/bert-base-multilingual-cased

resultsfpath: ./midterm-replication-jordan-renzo/predictions/pred_simple_agrmt.tsv
datafpath: ./midterm-replication-jordan-renzo/test_cases/eval_tsv_files/english/simple_agrmt.tsv
resultsfpath: ./midterm-replication-jordan-renzo/results/results_simple_agrmt.tsv
save: by_word, by_pair, by_cond
