exp: MinimalPair

mode: 
    - evaluate
    - analyze

models:
    hf_masked_model:
      - google-bert/bert-base-multilingual-cased

predfpath: ./midterm-replication-jordan-renzo/predictions/pred_obj_rel_within_anim.tsv
datafpath: ./midterm-replication-jordan-renzo/test_cases/eval_tsv_files/german/obj_rel_within_anim.tsv
resultsfpath: ./midterm-replication-jordan-renzo/results/results_obj_rel_within_anim.tsv
save: by_pair
