exp: MinimalPair

mode: 
    - evaluate
    - analyze

models:
    hf_causal_model:
      - mbert-base-multilingual-cased

predfpath: ./predictions/pred_prep_anim.tsv
datafpath: ./data/./test_cases/eval_tsv_files/german/prep_anim.tsv
resultsfpath: ./results/results_prep_anim.tsv
save: by_word, by_pair, by_cond
