exp: MinimalPair

device: cuda

mode: 
    - evaluate
    - analyze

models:
    hf_masked_model:
      - bert-base-uncased

predfpath: ./midterm-replication-jordan-renzo/predictions/pred_reflexive_sent_comp.tsv
datafpath: ./midterm-replication-jordan-renzo/test_cases/eval_tsv_files/english/reflexive_sent_comp.tsv
resultsfpath: ./midterm-replication-jordan-renzo/results/results_reflexive_sent_comp.tsv
save: by_pair
