exp: MinimalPair

device: cuda

mode: 
    - evaluate
    - analyze

models:
    hf_masked_model:
      - bert-base-uncased

predfpath: ./midterm-replication-jordan-renzo/predictions/pred_subj_rel.tsv
datafpath: ./midterm-replication-jordan-renzo/test_cases/eval_tsv_files/english/subj_rel.tsv
resultsfpath: ./midterm-replication-jordan-renzo/results/results_subj_rel.tsv
save: by_pair
