exp: MinimalPair

mode: 
    - evaluate
    - analyze

models:
    hf_causal_model:
      - google-bert/bert-base-multilingual-cased

resultsfpath: ./midterm-replication-jordan-renzo/predictions/pred_long_vp_coord.tsv
datafpath: ./midterm-replication-jordan-renzo/test_cases/eval_tsv_files/hebrew/long_vp_coord.tsv
resultsfpath: ./midterm-replication-jordan-renzo/results/results_long_vp_coord.tsv
save: by_word, by_pair, by_cond
