exp: MinimalPair

device: cuda

mode: 
    - evaluate
    - analyze

models:
    hf_masked_model:
      - google-bert/bert-base-multilingual-cased

predfpath: ./midterm-replication-jordan-renzo/predictions/pred_prep_anim.tsv
datafpath: ./midterm-replication-jordan-renzo/test_cases/eval_tsv_files/hebrew/prep_anim.tsv
resultsfpath: ./midterm-replication-jordan-renzo/results/results_prep_anim.tsv
save: by_pair
