exp: MinimalPair

device: cuda

mode: 
    - evaluate
    - analyze

models:
    hf_masked_model:
      - google-bert/bert-base-multilingual-cased

predfpath: ./midterm-replication-jordan-renzo/predictions/pred_simple_agrmt.tsv
datafpath: ./midterm-replication-jordan-renzo/test_cases/eval_tsv_files/russian/simple_agrmt.tsv
resultsfpath: ./midterm-replication-jordan-renzo/results/results_simple_agrmt.tsv
save: by_pair
