exp: MinimalPair

mode: 
    - evaluate
    - analyze

models:
    hf_causal_model:
      - mbert-base-multilingual-cased

predfpath: ./predictions/pred_vp_coord.tsv
datafpath: ./data/./test_cases/eval_tsv_files/russian/vp_coord.tsv
resultsfpath: ./results/results_vp_coord.tsv
save: by_word, by_pair, by_cond
