exp: MinimalPair

mode: 
    - evaluate
    - analyze

models:
    hf_causal_model:
      - mbert-base-multilingual-cased

predfpath: ./predictions/pred_subj_rel.tsv
datafpath: ./data/./test_cases/eval_tsv_files/french/subj_rel.tsv
resultsfpath: ./results/results_subj_rel.tsv
save: by_word, by_pair, by_cond
